version: '3.9'

services:
  app:
    container_name: app
    build: ./
    # command: python manage.py runserver 0.0.0.0:8000
    entrypoint: tail -f /dev/null
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./envs/.env
    networks:
      - sites_django_network

  db:
    image: postgres:14.3-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./envs/.postgres
    networks:
      - sites_django_network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - sites_django_network

volumes:
  postgres_data:

networks:
  sites_django_network:
    driver: bridge